"""add lead_status_id to user

Revision ID: 31091ae24e6c
Revises: 70f2efe88acd
Create Date: 2026-08-14 16:52:36.788335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31091ae24e6c'
down_revision = '70f2efe88acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lead_statuses', ['lead_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lead_status_id')

    # ### end Alembic commands ###
