"""add platform_ticket to trade

Revision ID: bb00dbd66f4a
Revises: f33d0d6954ac
Create Date: 2026-08-27 15:43:59.438655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb00dbd66f4a'
down_revision = 'f33d0d6954ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_ticket', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('platform_ticket')

    # ### end Alembic commands ###
