"""add status_type to lead_statuses

Revision ID: f33d0d6954ac
Revises: 9c4c2b7a8e91
Create Date: 2026-08-20 11:05:42.836748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33d0d6954ac'
down_revision = '9c4c2b7a8e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    with op.batch_alter_table('lead_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_statuses', schema=None) as batch_op:
        batch_op.drop_column('status_type')

    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
